services:
  - type: web
    name: narubranch-web
    env: docker
    envVars:
      - key: APP_NAME
        value: NaruBranch
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:QmO0bjKWqqpj+E9jzz4c9F1ploYlebDjTOIX3KI/5ZU=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: PORT
        value: 10000
      - key: APP_URL
        value: https://narubranch-web.onrender.com
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.hostinger.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: official@narubranchtech.id
      - key: MAIL_PASSWORD
        value: N@ru2026
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: official@narubranchtech.id
      - key: MAIL_FROM_NAME
        value: NaruBranch
